version: '3'

services:
  db:
    image: postgres:14.5
    restart: always
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
    volumes:
        - postgres:/var/lib/postgresql/data
  server:
    build: ./server
    env_file: 
      - dev.env
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: server
    volumes:
      - ./server/src:/app
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on: 
      - db
  frontend:
    build: ./frontend
    command: bash -c "npm run prebuild && npm run start"
    container_name: frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/dist:/app/dist
    ports:
      - "80:8080"
    restart: on-failure

volumes:
  postgres:
