version: '3'

services:
  server:
    build: ./server
    env_file: 
      - dev.env
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: server
    volumes:
      - ./server/src:/app
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    command: bash -c "npm run prebuild && npm run start"
    container_name: frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/dist:/app/dist
    ports:
      - "80:8080"
