# Generated by Django 4.0.6 on 2022-07-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_rename_str_id_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
