# Generated by Django 4.0.6 on 2022-07-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='str_id',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
