# Generated by Django 4.0.6 on 2022-07-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_remove_record_id_alter_record_str_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='str_id',
            new_name='id',
        ),
    ]
