# Generated by Django 4.0.6 on 2022-08-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_record_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
